[profile.default]
src = "src"
out = "out"
libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@gnosis-guild/=node_modules/@gnosis-guild/",
    "@gnosis.pm/=node_modules/@gnosis.pm/",
    "@openzeppelin/=node_modules/@openzeppelin/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
